param(
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$syncDir = Join-Path $repoRoot "sync"
$distDir = Join-Path $repoRoot "dist\sync"

New-Item -ItemType Directory -Force -Path $distDir | Out-Null

$mapPath = Join-Path $syncDir "shawn-function-map.json"
$map = Get-Content -LiteralPath $mapPath -Raw -Encoding UTF8 | ConvertFrom-Json

Copy-Item -LiteralPath $mapPath -Destination (Join-Path $distDir "shawn-function-map.json") -Force

function Get-FunctionSummary {
    param($Map)
    $lines = New-Object System.Collections.Generic.List[string]
    foreach ($category in $Map.categories) {
        $lines.Add("")
        $lines.Add("## $($category.id) $($category.name)")
        foreach ($item in $category.items) {
            $status = if ($item.status) { " [$($item.status)]" } else { "" }
            $lines.Add("- $($item.id) $($item.name)$status")
            foreach ($child in $item.children) {
                $childStatus = if ($child.status) { " [$($child.status)]" } else { "" }
                $lines.Add("  - $($child.id) $($child.name)$childStatus")
            }
        }
    }
    return ($lines -join "`r`n")
}

$summary = Get-FunctionSummary -Map $map
$syncVersion = $map.version

$tgSource = Get-Content -LiteralPath (Join-Path $syncDir "tg-help-source.md") -Raw -Encoding UTF8
$tgText = @"
$tgSource

---
Function Quick Reference:
$summary

Generated From: $syncVersion
"@
Set-Content -LiteralPath (Join-Path $distDir "tg-help.txt") -Value $tgText -Encoding UTF8

$publicDriveSource = Get-Content -LiteralPath (Join-Path $syncDir "public-drive-guide-source.md") -Raw -Encoding UTF8
$publicDrive = @"
$publicDriveSource

---
Shawn Function Quick Reference:
$summary

Generated From: $syncVersion
"@
Set-Content -LiteralPath (Join-Path $distDir "public-drive-guide.md") -Value $publicDrive -Encoding UTF8

$promptSource = Get-Content -LiteralPath (Join-Path $syncDir "prompt-site-guide-source.md") -Raw -Encoding UTF8
$encodedPrompt = [System.Net.WebUtility]::HtmlEncode($promptSource)
$encodedSummary = [System.Net.WebUtility]::HtmlEncode($summary)
$html = @"
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shawn Prompt Site Guide</title>
  <style>
    body { font-family: "Microsoft YaHei", Arial, sans-serif; margin: 0; background: #f5f7fb; color: #17202a; }
    header { padding: 32px 28px; background: #101820; color: white; }
    main { max-width: 980px; margin: 0 auto; padding: 28px; }
    section { background: white; border: 1px solid #e5e8ef; border-radius: 10px; padding: 22px; margin-bottom: 18px; }
    pre { white-space: pre-wrap; line-height: 1.8; font-size: 15px; }
    .tag { display: inline-block; padding: 4px 10px; border-radius: 999px; background: #e8f1ff; color: #175cc4; font-size: 13px; }
  </style>
</head>
<body>
  <header>
    <div class="tag">Shawn Sync</div>
    <h1>Shawn Prompt Site Guide</h1>
    <p>Generated by Shawn-Core sync script. Source version: $syncVersion</p>
  </header>
  <main>
    <section>
      <pre>$encodedPrompt</pre>
    </section>
    <section>
      <h2>Function Quick Reference</h2>
      <pre>$encodedSummary</pre>
    </section>
  </main>
</body>
</html>
"@
Set-Content -LiteralPath (Join-Path $distDir "prompt-site-guide.html") -Value $html -Encoding UTF8

if (-not $Quiet) {
    Write-Output "Generated sync files:"
    Write-Output (Join-Path $distDir "tg-help.txt")
    Write-Output (Join-Path $distDir "prompt-site-guide.html")
    Write-Output (Join-Path $distDir "public-drive-guide.md")
    Write-Output (Join-Path $distDir "shawn-function-map.json")
}
